# Generated by Django 4.1.3 on 2022-11-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
    ]
